# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d2a9043ff72284e66b8186e1af6c010ac5b5737b9a01db73bf038bec187a6b39092b30f61dd8669b99aba8cc5cea8d9f5775da59090cf5f25ac253bb22342803

test:
  secret_key_base: 630f56954a32373457c6137fb85593db924512b4690a2de21c341d76d7dda78bfda0a44bf207f55e02e8708e0a66b4375217e93be2770776a01cc0903ef40edf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
